
KEYS = [
  "band",
  "instruments",
  "school",
  "year",
  "hair",
  "eyes",
  "height",
]

CHARACTERS = [
  {
    "name": "户山香澄",
    "aliases": ["kasumi", "toyama kasumi", "hushanxiangcheng","ksm"],
    "band": "Poppin'Party",
    "instruments": ["吉他", "主唱"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "棕色",
    "eyes": "紫色",
    "height": 156,
    "image": "assets/avatars/kasumi.png"
  },
  {
    "name": "花园多惠",
    "aliases": ["tae", "hanazono tae", "huayuanduohui", "otae", "o tae", "o-tae"],
    "band": "Poppin'Party",
    "instruments": ["吉他"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "黑色",
    "eyes": "黄绿色",
    "height": 164,
    "image": "assets/avatars/tae.png"
  },
  {
    "name": "市谷有咲",
    "aliases": ["Arisa", "Ichigaya", "shiguyouxiao"],
    "band": "Poppin'Party",
    "instruments": ["键盘手"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "金色",
    "eyes": "金色",
    "height": 152,
    "image": "assets/avatars/arisa.png"
  },
  {
    "name": "山吹沙绫",
    "aliases": ["saya", "yamabuki", "shanchuishaling"],
    "band": "Poppin'Party",
    "instruments": ["鼓手"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "棕色",
    "eyes": "蓝色",
    "height": 157,
    "image": "assets/avatars/saya.png"
  },
  {
    "name": "牛込里美",
    "aliases": ["rimi", "ushigome", "niuyulimei"],
    "band": "Poppin'Party",
    "instruments": ["贝斯手"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "黑色",
    "eyes": "棕色",
    "height": 150,
    "image": "assets/avatars/rimi.png"
  },
  {
    "name": "美竹兰",
    "aliases": ["ran", "mitake ran", "meizhulan"],
    "band": "Afterglow",
    "instruments": ["吉他", "主唱"],
    "school": "羽丘女子学园",
    "year": 3,
    "hair": "黑色",
    "eyes": "粉色",
    "height": 157,
    "image": "assets/avatars/ran.png"
  },
  {
    "name": "上原绯玛丽",
    "aliases": ["himari", "uehara himari", "shangyuanfeimali"],
    "band": "Afterglow",
    "instruments": ["贝斯手"],
    "school": "羽丘女子学园",
    "year": 3,
    "hair": "粉色",
    "eyes": "绿色",
    "height": 155,
    "image": "assets/avatars/himari.png"
  },
  {
    "name": "羽泽鸫",
    "aliases": ["tsugumi", "hazawa tsugumi", "yuzedong"],
    "band": "Afterglow",
    "instruments": ["键盘手"],
    "school": "羽丘女子学园",
    "year": 3,
    "hair": "棕色",
    "eyes": "棕色",
    "height": 156,
    "image": "assets/avatars/tsugumi.png"
  },
  {
    "name": "宇田川巴",
    "aliases": ["tomoe", "udagawa tomoe", "yutianchuanba"],
    "band": "Afterglow",
    "instruments": ["鼓手"],
    "school": "羽丘女子学园",
    "year": 3,
    "hair": "红色",
    "eyes": "绿色",
    "height": 168,
    "image": "assets/avatars/tomoe.png"
  },
  {
    "name": "青叶摩卡",
    "aliases": ["moca", "aoba moca", "qingyemoka"],
    "band": "Afterglow",
    "instruments": ["吉他"],
    "school": "羽丘女子学园",
    "year": 3,
    "hair": "银色",
    "eyes": "青色",
    "height": 158,
    "image": "assets/avatars/moca.png"
  },
  {
    "name": "千早爱音",
    "aliases": ["anon", "chihaya anon", "qianzaoaiyin"],
    "band": "MyGO!!!!!",
    "instruments": ["吉他"],
    "school": "羽丘女子学园",
    "year": 1,
    "hair": "粉色",
    "eyes": "灰色",
    "height": 160,
    "image": "assets/avatars/anon.png"
  },
  {
    "name": "高松灯",
    "aliases": ["takamatsu tomori", "tomori", "tomorin","gaosongdeng"],
    "band": "MyGO!!!!!",
    "instruments": ["主唱"],
    "school": "羽丘女子学园",
    "year": 1,
    "hair": "灰色",
    "eyes": "粉色",
    "height": 155,
    "image": "assets/avatars/tomori.png"
  },
  {
    "name": "长崎素世",
    "aliases": ["nagasaki soyo", "soyo", "soyorin","changqisushi","changqishuangshi"],
    "band": "MyGO!!!!!",
    "instruments": ["贝斯手"],
    "school": "月之森女子学园",
    "year": 1,
    "hair": "棕色",
    "eyes": "蓝色",
    "height": 162,
    "image": "assets/avatars/soyo.png"
  },
  {
    "name": "椎名立希",
    "aliases": ["shiina taki", "taki", "rikki","zhuiminglixi"],
    "band": "MyGO!!!!!",
    "instruments": ["鼓手"],
    "school": "花咲川女子学园",
    "year": 1,
    "hair": "黑色",
    "eyes": "紫色",
    "height": 156,
    "image": "assets/avatars/taki.png"
  },
  {
    "name": "要乐奈",
    "aliases": ["kaname rana", "rana", "yaolenai","mao"],
    "band": "MyGO!!!!!",
    "instruments": ["吉他"],
    "school": "花咲川女子学园",
    "year": 0,
    "hair": "银色",
    "eyes": "异瞳",
    "height": 150,
    "image": "assets/avatars/rana.png"
  },
  {
    "name": "丰川祥子",
    "aliases": ["togawa sakiko", "saki", "fengchuanxiangzi","oblivionis"],
    "band": "Ave Mujica",
    "instruments": ["键盘手"],
    "school": "羽丘女子学园",
    "year": 1,
    "hair": "蓝色",
    "eyes": "金色",
    "height": 155,
    "image": "assets/avatars/saki.png"
  },
  {
    "name": "三角初华",
    "aliases": ["misumi uika", "uika","sanjiaochuhua","doloris"],
    "band": "Ave Mujica",
    "instruments": ["吉他","主唱"],
    "school": "花咲川女子学园",
    "year": 1,
    "hair": "金色",
    "eyes": "紫色",
    "height": 160,
    "image": "assets/avatars/uika.png"
  },
  {
    "name": "若叶睦",
    "aliases": ["wakaba mutsumi", "muzimi","ruoyemu","motisi","mortis"],
    "band": "Ave Mujica",
    "instruments": ["吉他"],
    "school": "月之森女子学园",
    "year": 1,
    "hair": "绿色",
    "eyes": "金色",
    "height": 153,
    "image": "assets/avatars/mzm.png"
  },
  {
    "name": "八幡海铃",
    "aliases": ["yahata umiri","timoris","bafanhailing"],
    "band": "Ave Mujica",
    "instruments": ["贝斯手"],
    "school": "花咲川女子学园",
    "year": 1,
    "hair": "黑色",
    "eyes": "绿色",
    "height": 158,
    "image": "assets/avatars/umiri.png"
  },
  {
    "name": "祐天寺若麦",
    "aliases": ["yutenji nyamu","amoris","miaomuqin","youtiansiruomai","damao"],
    "band": "Ave Mujica",
    "instruments": ["鼓手"],
    "school": "都立艺术学院高中",
    "year": 1,
    "hair": "紫色",
    "eyes": "粉色",
    "height": 164,
    "image": "assets/avatars/nyamu.png"
  },
  {
    "name": "丸山彩",
    "aliases": ["maruyama aya","aya","wanshancai"],
    "band": "Pastel*Palettes",
    "instruments": ["主唱"],
    "school": "四叶女子大学",
    "year": 4,
    "hair": "粉色",
    "eyes": "粉色",
    "height": 156,
    "image": "assets/avatars/aya.png"
  },
  {
    "name": "冰川日菜",
    "aliases": ["hikawa hina","hina","bingchuanricai"],
    "band": "Pastel*Palettes",
    "instruments": ["吉他"],
    "school": "庆鹏女子大学",
    "year": 4,
    "hair": "青色",
    "eyes": "绿色",
    "height": 156,
    "image": "assets/avatars/hina.png"
  },
  {
    "name": "白鹭千圣",
    "aliases": ["Shirasagi Chisato","chisato","bailuqiansheng"],
    "band": "Pastel*Palettes",
    "instruments": ["贝斯手"],
    "school": "四叶女子大学",
    "year": 4,
    "hair": "金色",
    "eyes": "紫色",
    "height": 152,
    "image": "assets/avatars/chisato.png"
  },
  {
    "name": "大和麻弥",
    "aliases": ["yamato maya","maya","dahemami"],
    "band": "Pastel*Palettes",
    "instruments": ["鼓手"],
    "school": "庆鹏女子大学",
    "year": 4,
    "hair": "棕色",
    "eyes": "绿色",
    "height": 161,
    "image": "assets/avatars/maya.png"
  },
  {
    "name": "若宫伊芙",
    "aliases": ["wakamiya","eve","ruogongyifu"],
    "band": "Pastel*Palettes",
    "instruments": ["键盘手"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "银色",
    "eyes": "蓝色",
    "height": 163,
    "image": "assets/avatars/eve.png"
  },
  {
    "name": "凑友希那",
    "aliases": ["minato yukina","ykn","couyouxina"],
    "band": "Roselia",
    "instruments": ["主唱"],
    "school": "四叶女子大学",
    "year": 4,
    "hair": "银色",
    "eyes": "金色",
    "height": 155,
    "image": "assets/avatars/ykn.png"
  },
  {
    "name": "冰川纱夜",
    "aliases": ["hikawa sayo","sayo","bingchuanshaye"],
    "band": "Roselia",
    "instruments": ["吉他"],
    "school": "庆鹏女子大学",
    "year": 4,
    "hair": "青色",
    "eyes": "绿色",
    "height": 161,
    "image": "assets/avatars/sayo.png"
  },
  {
    "name": "今井莉莎",
    "aliases": ["imai lisa","lisa","jinjinglisha"],
    "band": "Roselia",
    "instruments": ["贝斯手"],
    "school": "四叶女子大学",
    "year": 4,
    "hair": "棕色",
    "eyes": "绿色",
    "height": 158,
    "image": "assets/avatars/lisa.png"
  },
  {
    "name": "宇田川亚子",
    "aliases": ["Udagawa Ako","ako","yutianchuanyazi"],
    "band": "Roselia",
    "instruments": ["鼓手"],
    "school": "羽丘女子学园",
    "year": 2,
    "hair": "紫色",
    "eyes": "红色",
    "height": 148,
    "image": "assets/avatars/ako.png"
  },
  {
    "name": "白金燐子",
    "aliases": ["Shirokane Rinko","rinko","baijinlinzi"],
    "band": "Roselia",
    "instruments": ["键盘手"],
    "school": "四叶女子大学",
    "year": 4,
    "hair": "黑色",
    "eyes": "紫色",
    "height": 157,
    "image": "assets/avatars/rinko.png"
  },
  {
    "name": "弦卷心",
    "aliases": ["Tsurumaki Kokoro","kokoro","kkr","xianjuanxin"],
    "band": "Hello, Happy World!",
    "instruments": ["主唱"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "金色",
    "eyes": "金色",
    "height": 155,
    "image": "assets/avatars/kkr.png"
  },
  {
    "name": "濑田薰",
    "aliases": ["Seta Kaoru","kaoru","laitianxun"],
    "band": "Hello, Happy World!",
    "instruments": ["吉他"],
    "school": "四叶女子大学",
    "year": 4,
    "hair": "紫色",
    "eyes": "红色",
    "height": 170,
    "image": "assets/avatars/kaoru.png"
  },
  {
    "name": "北泽育美",
    "aliases": ["Kitazawa Hagumi","hagumi","beizeyumei"],
    "band": "Hello, Happy World!",
    "instruments": ["贝斯手"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "橙色",
    "eyes": "红色",
    "height": 152,
    "image": "assets/avatars/hgm.png"
  },
  {
    "name": "松原花音",
    "aliases": ["Matsubara Kanon","kanon","songyuanhuayin","shuimu"],
    "band": "Hello, Happy World!",
    "instruments": ["鼓手"],
    "school": "庆鹏女子大学",
    "year": 4,
    "hair": "蓝色",
    "eyes": "紫色",
    "height": 156,
    "image": "assets/avatars/kanon.png"
  },
   {
    "name": "奥泽美咲",
    "aliases": ["Okusawa Misaki","aozemeixiao","mixieer","misaki"],
    "band": "Hello, Happy World!",
    "instruments": ["DJ"],
    "school": "花咲川女子学园",
    "year": 3,
    "hair": "黑色",
    "eyes": "灰色",
    "height": 157,
    "image": "assets/avatars/misaki.png"
  },
  {
    "name": "仓田真白",
    "aliases": ["Kurata Mashiro","cangtianzhenbai","mashiro","msr"],
    "band": "Morfonica",
    "instruments": ["主唱"],
    "school": "月之森女子学园",
    "year": 2,
    "hair": "银色",
    "eyes": "灰色",
    "height": 154,
    "image": "assets/avatars/msr.png"
  },
  {
    "name": "桐谷透子",
    "aliases": ["Kirigaya Tōko","toko","tonggutouzi"],
    "band": "Morfonica",
    "instruments": ["吉他"],
    "school": "月之森女子学园",
    "year": 2,
    "hair": "金色",
    "eyes": "棕色",
    "height": 164,
    "image": "assets/avatars/toko.png"
  },
  {
    "name": "广町七深",
    "aliases": ["Hiromachi Nanami","nanami","guangdingqishen"],
    "band": "Morfonica",
    "instruments": ["贝斯手"],
    "school": "月之森女子学园",
    "year": 2,
    "hair": "粉色",
    "eyes": "粉色",
    "height": 157,
    "image": "assets/avatars/nanami.png"
  },
  {
    "name": "二叶筑紫",
    "aliases": ["Futaba Tsukushi","tsukushi","eryezhuzi"],
    "band": "Morfonica",
    "instruments": ["鼓手"],
    "school": "月之森女子学园",
    "year": 2,
    "hair": "紫色",
    "eyes": "橙色",
    "height": 150,
    "image": "assets/avatars/tsukushi.png"
  },
  {
    "name": "八潮瑠唯",
    "aliases": ["Yashio Rui","rui","bachaoliuwei"],
    "band": "Morfonica",
    "instruments": ["小提琴"],
    "school": "月之森女子学园",
    "year": 2,
    "hair": "黑色",
    "eyes": "粉色",
    "height": 169,
    "image": "assets/avatars/rui.png"
  },
  {
    "name": "LAYER",
    "aliases": ["Wakana Rei","lei","layer","hezouruiyi"],
    "band": "RAISE A SUILEN",
    "instruments": ["主唱","贝斯手"],
    "school": "都立艺术学院高中",
    "year": 3,
    "hair": "黑色",
    "eyes": "蓝色",
    "height": 172,
    "image": "assets/avatars/layer.png"
  },
  {
    "name": "LOCK",
    "aliases": ["Asahi Rokka","lock","rokka","zhaoriliuhua"],
    "band": "RAISE A SUILEN",
    "instruments": ["吉他"],
    "school": "羽丘女子学园",
    "year": 2,
    "hair": "蓝色",
    "eyes": "绿色",
    "height": 155,
    "image": "assets/avatars/lock.png"
  },
  {
    "name": "MASKING",
    "aliases": ["Satō Masuki","masuki","masking","zuotengyimu"],
    "band": "RAISE A SUILEN",
    "instruments": ["鼓手"],
    "school": "白雪学园",
    "year": 3,
    "hair": "金色",
    "eyes": "金色",
    "height": 170,
    "image": "assets/avatars/msk.png"
  },
  {
    "name": "PAREO",
    "aliases": ["Nyūbara Reona","pareo","ruyuanlingwangna"],
    "band": "RAISE A SUILEN",
    "instruments": ["键盘手"],
    "school": "加茂川中央中学校",
    "year": 0,
    "hair": "双色",
    "eyes": "红色",
    "height": 162,
    "image": "assets/avatars/pareo.png"
  },
  {
    "name": "CHU²",
    "aliases": ["Tamade Chiyu","chuchu","chupingfang"],
    "band": "RAISE A SUILEN",
    "instruments": ["DJ"],
    "school": "塞洛西亚女子学校",
    "year": 3,
    "hair": "粉色",
    "eyes": "蓝色",
    "height": 140,
    "image": "assets/avatars/chuchu.png"
  },
]

'''
  {
    "name": "墨缇丝",
    "aliases": ["motisi","mortis"],
    "band": "Ave Mujica",
    "instruments": ["吉他"],
    "school": "月之森女子学园",
    "year": 1,
    "hair": "绿色",
    "eyes": "金色",
    "height": 153,
    "image": "assets/avatars/mts.png"
  },
'''